version: 2.1
jobs:
  compile:
   docker:
      - image: nexgang/ubuntu:latest
   steps:
      - run:
          command: |
            apt update && apt upgrade -y
            apt install -f -y git
            ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
            git clone --depth=1 https://github.com/fredslbn/whyred2.git -b main builder_kernel
            cd builder_kernel
            bash .circleci/whyred.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
